//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityFramework.Areas.Access.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Role()
        {
            this.RoleRoutes = new HashSet<RoleRoute>();
            this.RoleUsers = new HashSet<RoleUser>();
        }
    
        public System.Guid Id { get; set; }
        public int Sequence { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> DomainId { get; set; }
        public Nullable<System.Guid> OrganizationId { get; set; }
        public Nullable<System.Guid> GroupId { get; set; }
        public Nullable<System.Guid> OfficeId { get; set; }
        public Nullable<System.Guid> ShopId { get; set; }
    
        public virtual Domain Domain { get; set; }
        public virtual Group Group { get; set; }
        public virtual Office Office { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleRoute> RoleRoutes { get; set; }
        public virtual Shop Shop { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleUser> RoleUsers { get; set; }
    }
}
