//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityFramework.Areas.Access.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAreaAndRoleAndRoute
    {
        public int AreaSeq { get; set; }
        public int Seq { get; set; }
        public string AreaAndRole { get; set; }
        public System.Guid Id { get; set; }
        public System.Guid RoleId { get; set; }
        public System.Guid RouteId { get; set; }
        public string RoutePath { get; set; }
    }
}
