//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityFramework.Areas.Access.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwIsInRole
    {
        public System.Guid AreaAppId { get; set; }
        public Nullable<System.Guid> AreaId { get; set; }
        public string Area { get; set; }
        public Nullable<System.Guid> RoleId { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public System.Guid RouteId { get; set; }
        public string RoutePath { get; set; }
        public Nullable<System.Guid> RouteAppId { get; set; }
    }
}
