//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityFramework.Areas.Access.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRoleRoute
    {
        public System.Guid RoleId { get; set; }
        public System.Guid RouteId { get; set; }
        public Nullable<System.Guid> AppId { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string AppPath { get; set; }
        public string RoutePath { get; set; }
    }
}
