//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SecurityFramework.Areas.Access.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRole
    {
        public System.Guid Id { get; set; }
        public int Sequence { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> AreaId { get; set; }
    }
}
